# Generated by Django 5.1.7 on 2025-03-20 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='BookingDat',
            new_name='BookingDate',
        ),
    ]
